### PR TITLE
Switch JTS dependency from com.vividsolutions to org.locationtech.jts

### PR DESCRIPTION
**Pull request by MMcM**
See https://github.com/locationtech/jts/blob/master/MIGRATION.md

### CODE REVIEW

**Comment by geophile** [comment]
Thanks for the update.

**Comment by MMcM** [comment]
I looked in Maven Central and there are 2.1.0 (add `accelerateAncestorSearch`) and 2.2.0 (change `SpatialJoinIterator`) versions. But master here was 2.0.5. Is there something somewhere else that needs to be merged before cutting a new release?

**Comment by geophile** [comment]
It's been a long time since I worked on this project. I'll figure this out
and get back to you.

**Comment by geophile** [comment]
Git is now up to date, with my latest and your JTS changes. I am having
some trouble with credentials uploading this version to maven central.
Working on it -- are you blocked?

**Comment by MMcM** [comment]
> are you blocked?

I am cooking up a pull-request for https://github.com/FoundationDB/fdb-record-layer. I can get it working with a local copy, so I'm not completely stuck right now.

**Comment by geophile** [comment]
2.3 is in maven.

**Pull request merged**
